### ISSUE TITLE
production vs development vs debug

### ISSUE THREAD

**Issue by Martii** [jwarkentin/node-monkey#29]
Firstly I just wanted to say this is one of the more clever packages for node projects that I've seen to date. Thank you for your continued effort with this.

Secondly to the questions/explanation for a feature enhancement.

Currently we would like to use your package in our site but it needs a little tweaking that seems to be best served in this package so we don't collide with your `replaceConsole`.

What we are looking for is a `config` setting that encompasses `production`, `development` and native node `debug` mode and a "null" mode. e.g. send `console` method messages to the equivalent of /dev/nul output.

I've done a little preliminary research into this and the following conditionals can achieve testing the environment:

``` javascript
// Usually invoked by deployment
var isProduction = process.env.NODE_ENV === 'production';
```

``` javascript
// Usually invoked by `$ node index.js`
var isDevelopment = process.env.NODE_ENV !== 'production';
```

``` javascript
// Usually invoked by `$ node debug index.js`
var isDebug = typeof v8debug === 'object';
```

What I am currently missing is a solid understanding of this project to commit a pull request at this time *(this will most likely change hopefully in the near future)* and matching some of your styling/naming conventions.

What I'd like to know is if you would be willing to add some variant of these to your options that encompasses all of these? I read the statement you have in the [README.md](https://github.com/jwarkentin/node-monkey/blob/9e8d5782320c3a02d182fc57c48a0329d23e1d05/README.md) of:

> NodeMonkey is primarily designed for debugging and for now should only be used for such.

... which is one of our goals however since you said:

> I haven't implemented any sort of authorization to prevent anyone from gaining access to the data that is dumped out.

... this feature request might be a good minimum start.

Please let me know and if I can assist in any additional way within my means. Thank you for the consideration... once again very "kewl" package.

**Comment by jwarkentin** [comment]
As far as I can tell, all the issues discussed here should be resolved with the new release. Review the documentation and let me know if you don't think this is resolved.
