### ISSUE TITLE
expose node-monkey stream if app already uses bunyan

### ISSUE THREAD

**Issue by abelnation** [jwarkentin/node-monkey#32]
It would be really nice if node-monkey expose a bunyan-stream for sending the data to the client web page.  That way, if the app already uses bunyan (ours does!), then we can just hook in an additional stream to the bunyan logger.

Thoughts?

**Comment by jwarkentin** [comment]
I like this idea. I will try and implement it soon (maybe even tonight).

**Comment by jwarkentin** [comment]
I just pushed v0.2.15 to expose the bunyan stream. I'm interested in your feedback if it's not quite what you are looking for. I made it extract the message and display that, but also display the full log record object on the same line in the browser in case there are other properties you are interested in.

**Comment by abelnation** [comment]
Great! I'll try and integrate it in the next week if I can! Glad you liked
the idea.

On Thu, Mar 5, 2015 at 12:49 AM, Justin Warkentin <notifications@github.com>
wrote:

> I just pushed v0.2.15 to expose the bunyan stream. I'm interested in your
> feedback if it's not quite what you are looking for. I made it extract the
> message and display that, but also display the full log record object on
> the same line in the browser in case there are other properties you are
> interested in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jwarkentin/node-monkey/issues/32#issuecomment-77327304>
> .
>



-- 
Abel Allison
abel.allison@gmail.com
713-557-4984
