### ISSUE TITLE
output to app console

### ISSUE THREAD

**Issue by staminna** [jwarkentin/node-monkey#34]
"As an alternative to viewing output through this page, you can also view output in the console of your own web application by including the following lines (adjust the host and port as necessary, this is based on the defaults)"
<script type="text/javascript" src="http://0.0.0.0:50500/socket.io/socket.io.js"></script>
<script type="text/javascript" src="http://0.0.0.0:50500/lodash.js"></script>
<script type="text/javascript" src="http://0.0.0.0:50500/cycle.js"></script>
<script type="text/javascript" src="http://0.0.0.0:50500/client.js"></script>

So it seems I need to add this code somewhere to my server.js file, but when I call 

$ node server.js
^

SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

of course this makes sense, but I don't really know how to do this in nodejs.
Can you help with a simple example?
Thanks

**Comment by jwarkentin** [comment]
Those `<script>` tags just need to go in the `<head>` of your HTML output. I don't know what your code looks like specifically but wherever you dump out HTML to the web browser is where you need to insert those lines.
