### ISSUE TITLE
scripts not found

### ISSUE THREAD

**Issue by staminna** [jwarkentin/node-monkey#35]
info  - socket.io started
------------------
NodeMonkey started
To inspect output, open a browser to: http://localhost:5000
------------------

GET /socket.io/socket.io.js HTTP/1.1
Host: localhost:5000
Connection: keep-alive
Cache-Control: max-age=0
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
DNT: 1
Referer: http://localhost:5000/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,pt;q=0.6
Cookie: io=9XZZK95WyrJvPVURAAAA; session_id=e466c802-9dc6-4ce4-af00-8bb1910da78a

Response headers: HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Type: text/html
Date: Thu, 26 Nov 2015 21:03:06 GMT
Connection: keep-alive
Content-Length: 35

It's looking for the file in:
http://localhost:5000/socket.io/socket.io.js

from the root of the filesystem directory: /node_modules/node-monkey/node_modules/socket.io/lib/socket.io.js

**Comment by jwarkentin** [comment]
Any issues you may have had should be resolved with the latest release. Let me know if issues persist.
