### ISSUE TITLE
Doesn't work with BrowserSync

### ISSUE THREAD

**Issue by ericbiewener** [jwarkentin/node-monkey#36]
When using BrowserSync, the page won't load -- I just see the spinner going round and round on the tab in Chrome. If I wrap `require('node-monkey').start()` in `setTimeout()`. However, that defeats the purpose since it causes node monkey to not start until all the server code has already run (and thus all logs output to Terminal).

**Comment by jwarkentin** [comment]
I've never used BrowserSync. I'll have to figure out how it works and why it doesn't work. I could add an option to dump the logs to a file and then allow reviewing them in the console later. That shouldn't be too difficult but I don't know if it's the best solution.

**Comment by ericbiewener** [comment]
At a minimum I can tell you that BrowserSync requires you to open your site
on a port different from the one configured in the node script that creates
your server. Perhaps that is part of the issue. Happy to help debug in any
way I can.

**Comment by jwarkentin** [comment]
Can you look over the new release and let me know if it resolves your BrowserSync issue? It's pretty flexible in how you use it now and allows any combination of options to make things work.
