### ISSUE TITLE
console.info

### ISSUE THREAD

**Issue by pasqLisena** [jwarkentin/node-monkey#38]
Why not supporting also `console.info`?
It is the only one missing among the filters of webkit console :smiley: 
![image](https://cloud.githubusercontent.com/assets/4126222/14858986/749fea92-0ca2-11e6-8888-a9f1704c0212.png)

**Comment by jwarkentin** [comment]
Good call. It's been a long time since I've maintained this project but now that I have some sort of work/life balance I've just embarked on a rewrite. I should have something ready soon.

**Comment by jwarkentin** [comment]
Resolved with latest release
