### ISSUE TITLE
DeprecationWarning: process.EventEmitter

### ISSUE THREAD

**Issue by preflight** [jwarkentin/node-monkey#39]
Running Node 6.1.0, I'm seeing the following warning on each reload. Is there a way to suppress or correct it?

```
(node:3684) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.  -- Called from internal/process/warning.js:24:17(function process.on)
```

![image](https://cloud.githubusercontent.com/assets/2300813/16901142/0bcb81e6-4c00-11e6-930d-b2a069a746b7.png)

**Comment by marlic7** [comment]
+1

**Comment by jwarkentin** [comment]
Resolved with latest release
