### ISSUE TITLE
'guest' auth fails

### ISSUE THREAD

**Issue by tconroy** [jwarkentin/node-monkey#41]
Hi,

I'm running a simple Express ES6 server which uses `babel-node`.

I'm trying to get node-monkey up and running with its own (default) configuration. I can hit the server just fine, and am prompted for authentication. I enter the default username: guest, password: guest, but it just repeatedly asks me for my login. An empty object is logged to the console with a "Auth failed" message.

Is there any additional config required? All I've done is included this line in my server.js:

`monkey = require('node-monkey')();`

**Comment by jwarkentin** [comment]
I cannot reproduce your problem. If I do a fresh install of Node Monkey and then put the same code as you, it prompts and authentication works. If you can answer a few questions it might help:

1. What OS are you using?
2. What version of Node are you using?
3. Were there any errors when you installed Node Monkey?

Part of the installation requires compiling the scrypt module for authentication. If that fails then authentication will not work. Also, you may want to update as I just pushed a new release with an important bug fix.

**Comment by tconroy** [comment]
I'll try to get a minimal example up ( this is integrating into a fairly large codebase so there is a chance the conflict is on my end).

to answer the other questions:

1. OSX 10.11.4
2. Node 5.5.0, NPM 2.14.22
3. Nope, no installation errors as far as I could tell.

**Comment by jwarkentin** [comment]
Ok, that was helpful. I tracked it down to a change in the built-in Buffer module between Node 5.5.0 and 6.x. I just released a new update that fixes authentication for older versions of Node.
