### ISSUE TITLE
Auth failed: User 'guest' does not exist

### ISSUE THREAD

**Issue by laurenskling** [jwarkentin/node-monkey#42]
when i start as per documentation:
```
let monkey = require('node-monkey')({});
monkey.attachConsole();
```
i see the message:
```[WARN] No users detected. You can login with default user 'guest' and password 'guest' when prompted.
This user will be disabled when you create a user account.```

but when i try to log in as `guest` with `guest` the console gives: 
`Auth failed: User 'guest' does not exist`

node-monkey: ^1.0.0-beta.4
node: 6.3.0
npm: 3.10.3

**Comment by jwarkentin** [comment]
Is it possible your `NODE_ENV` is set to `production`? The guest user won't exist without a user file if that's the case. I need to fix the messaging when that happens. If it is not set to `production` then there is definitely something weird happening and it would be helpful to know what OS you are using.

**Comment by laurenskling** [comment]
That was it! I was running in `production` mode, thanks for the help.
