### ISSUE TITLE
Disable authentication on development

### ISSUE THREAD

**Issue by pasqLisena** [jwarkentin/node-monkey#44]
Is it possible to disable the authentication login during the development (i.e. on `localhost`) ?
Sometimes you need to restart the server often and _nomo_ asks you for credential at each restart.

**Comment by jwarkentin** [comment]
It will ask you for credentials if you refresh the page but it will not ask if you just restart the server. It will automatically reconnect and re-authenticate without asking you. I know there has been a reconnection issue that often requires you to refresh the page though. I am about to do a release that should fix that.

**Comment by jwarkentin** [comment]
I have just cut a new release. Give it a try and let me know if you have any issues. You should not have to refresh the browser page at all. Any time you restart the server the browser should automatically reconnect within 5 seconds and show all output from the server without prompting for credentials again.

**Comment by pasqLisena** [comment]
Thank you @jwarkentin! Now it works without any problem :)
