### ISSUE TITLE
With NodeMonkey service Express Router() Object is not showing query(Query Parameters) in request object

### ISSUE THREAD

**Issue by hari-007** [jwarkentin/node-monkey#53]
After Adding NodeMonkey debugging service, I am not getting Request Object Query String of query property in Request Object of Express Route(). I know it looks kind a strange but half day of strange debugging and issue solving results as NodeMonkey service is somehow not enabling query object to be generated in express route 

I tested with express generated hello world ejs app & nodejs rest API app with express too. Here is the example when i tried to fire the request with postman

![screenshot from 2018-01-21 16-00-53](https://user-images.githubusercontent.com/5758223/35199538-ff8f8c14-fec4-11e7-8645-6c7ce3d66754.png)

And i have one more question. Previously (6 or 7 months before) i used the same kind of node-monkey module from npm. At that time that node-monkey is not a stable version, So i was depended on version **0.1.26** or something around **0.** . Such an extent it used to work well and restart automatically when npm start triggers and it works well as like this on port number 50500. the way i used to integrate that is like this 

eg:  require(node-monkey).start({host:'localhost', port: 50500});
**So is this repository is the one which i used previously ?**

**Comment by marlic7** [comment]
This is probably because of mixing 2 web frameworks. 
In my app I use expressjs and NodeMonkey use restify so req.query disappear.

See similar problem description:
https://stackoverflow.com/questions/45928112/query-string-variables-still-empty-in-express-4

**Comment by jwarkentin** [comment]
While I should probably swap out restify as the default since express is more popular, it's worth noting that it has always been possible to attach to any express-like server, as shown in the docs with an express example [here](https://github.com/jwarkentin/node-monkey/blob/master/doc/usage/server.md#provide-your-own).
