### ISSUE TITLE
code": "ResourceNotFound", "message": "/; caused by Error: ENOENT: no such file or directory, stat ..../node_modules/node-monkey/dist/index.html

### ISSUE THREAD

**Issue by frankyeyq** [jwarkentin/node-monkey#61]
node index.js
index.js:
let NodeMonkey = require("node-monkey")
NodeMonkey()
console.log('test')

**Comment by frankyeyq** [comment]
I copy index.html
<!DOCTYPE html>
<html>
  <head><script src="monkey.js"></script></head>
  <body>
    Open your console to see output
    <script type="text/javascript">
      ;(function () {
        monkey.init()
      })()
    </script>
  </body>
</html>
to dist/, then it works

**Comment by samislam** [comment]
Yes, that works, the author should fix this

**Comment by samislam** [comment]
Here is the solution in more details:
1. open node_modules.
2. navigate to **node-monkey** folder.
3. navigate to the **/dist** folder.
4. create a file called **index.html** there.
5. Paste the following code and save the file.
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script src="monkey.js"></script> 
    <script type="text/javascript"> ;(function () { monkey.init() })() </script>
</body>
</html>
```
7. in your browser go to `http://0.0.0.0:50500`
8. the default username and password are `guest` and `guest`
9. open your browser's console, and you should see that node-monkey is working now.

**Comment by jwarkentin** [comment]
I'll take a look at this. I have some updates in progress I need to finish so I'll be cutting a new release soon and I'll make sure the index file is in place on npm.

**Comment by jwarkentin** [comment]
This is fixed in the latest release.
